Swarm RAG
ulab-uiuc/research-town pull request #878
Opened 2024-11-17 23:05 UTC by timsanders256

Closes # 

## 📑 Description

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed
- [ ] Branch name follows `type/descript` (e.g. `feature/add-llm-agents`)
- [ ] Ready for code review

## ℹ Additional Information

2024-11-17 23:06 UTC, timsanders256 commented
Not complete, so please don't merge for now

2024-11-20 03:59 UTC, lwaekfjlk requested changes

2024-11-20 03:59 UTC, lwaekfjlk commented on pyproject.toml
> +nltk = "^3.9.1"
should still change these into optioinal

2024-11-20 03:59 UTC, lwaekfjlk commented on research_bench/proposal_writing.py
> +    # leader_profile = profile_db.get(name=profiles[0].name)[0]
why this is changed?

2024-11-20 03:59 UTC, lwaekfjlk commented on research_bench/proposal_writing.py
> +    # TODO
delete these TODOs.

2024-11-20 03:59 UTC, lwaekfjlk commented on research_bench/run_eval.py
> +    # gen_review = write_review(mode, gen_proposal, profiles, config)
delete these useless comments.

2024-11-20 03:59 UTC, lwaekfjlk commented on research_town/dbs/db_base.py
> +            # f"Creating instance of '{data.__class__.__name__}': '{data.model_dump()}'"
should we change this? What is the motivation for not shwoing model_dump? Toolong?

2025-03-05 02:40 UTC, closed without merging